"""added profile pic

Revision ID: 647a80348bb3
Revises: a9e02d40e4a8
Create Date: 2024-12-23 02:38:55.343714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647a80348bb3'
down_revision = 'a9e02d40e4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
