"""Add is_admin column to User model

Revision ID: a9e02d40e4a8
Revises: 
Create Date: 2024-12-19 09:37:51.594495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e02d40e4a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('Admin',
    sa.Column('adminID', sa.INTEGER(), nullable=False),
    sa.Column('admin_uname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('hashed_pass', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('adminID'),
    sa.UniqueConstraint('admin_uname')
    )
    # ### end Alembic commands ###
